# Generated by Django 3.2.4 on 2021-06-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.IntegerField(blank=True, default=None, null=True, unique=True)),
                ('CNS', models.IntegerField(blank=True, default=None, null=True, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('nomeMae', models.CharField(max_length=100)),
                ('nomeSocial', models.CharField(blank=True, max_length=100)),
                ('dataNascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('FEMININO', 'FEMININO'), ('MASCULINO', 'MASCULINO'), ('IGNORADO', 'IGNORADO')], max_length=10)),
                ('raca', models.CharField(choices=[('AMARELA', 'AMARELA'), ('BRANCA', 'BRANCA'), ('INDIGENA', 'INDIGENA'), ('NAO INFORMADA', 'NAO INFORMADA'), ('PARDA', 'PARDA'), ('PRETA', 'PRETA')], max_length=20)),
                ('telefone', models.IntegerField()),
                ('gestante', models.BooleanField()),
                ('puerpera', models.BooleanField()),
                ('pais', models.CharField(max_length=100)),
                ('UF', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=100)),
                ('zona', models.CharField(choices=[('RURAL', 'RURAL'), ('URBANA', 'URBANA')], max_length=6)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=10)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
