# Generated by Django 3.2.5 on 2021-07-09 17:45

import covidlocal.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imunobiologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imunobiologico', models.CharField(max_length=30)),
                ('doses', models.IntegerField()),
                ('dias_prox_dose', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', covidlocal.models.EmptyStringToNoneField(blank=True, default=None, max_length=11, null=True, unique=True)),
                ('CNS', covidlocal.models.EmptyStringToNoneField(blank=True, default=None, max_length=15, null=True, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('nomeMae', models.CharField(max_length=100)),
                ('nomeSocial', models.CharField(blank=True, max_length=100)),
                ('dataNascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('FEMININO', 'FEMININO'), ('MASCULINO', 'MASCULINO'), ('IGNORADO', 'IGNORADO')], max_length=10)),
                ('raca', models.CharField(choices=[('AMARELA', 'AMARELA'), ('BRANCA', 'BRANCA'), ('INDIGENA', 'INDIGENA'), ('NAO INFORMADA', 'NAO INFORMADA'), ('PARDA', 'PARDA'), ('PRETA', 'PRETA')], max_length=20)),
                ('telefone', models.IntegerField()),
                ('gestante', models.BooleanField()),
                ('puerpera', models.BooleanField()),
                ('pais', models.CharField(max_length=100)),
                ('UF', models.CharField(choices=[('', ''), ('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2)),
                ('municipio', models.CharField(max_length=100)),
                ('zona', models.CharField(choices=[('RURAL', 'RURAL'), ('URBANA', 'URBANA')], max_length=6)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=10)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perdas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimento', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('lote', models.CharField(max_length=100)),
                ('falha_equip', models.IntegerField()),
                ('falha_trans', models.IntegerField()),
                ('falta_energ', models.IntegerField()),
                ('frasc_trans', models.IntegerField()),
                ('imunobiologico', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='covidlocal.imunobiologico', verbose_name='Imunobiológico')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=100)),
                ('validade', models.DateField(null=True, verbose_name='Data de Validade do Lote')),
                ('imunobiologico', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='covidlocal.imunobiologico', verbose_name='Imunobiológico')),
            ],
        ),
        migrations.CreateModel(
            name='Imunizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comorbidades', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CIRROSE HEPATICA', 'CIRROSE HEPATICA'), ('DIABETES MELLITUS', 'DIABETES MELLITUS'), ('DOENCA NEUROLOGICA CRONICA', 'DOENCA NEUROLOGICA CRONICA'), ('DOENCA RENAL CRONICA', 'DOENCA RENAL CRONICA'), ('DOENCAS CARDIOVASCULARES E CEREBROVASCULARES', 'DOENCAS CARDIOVASCULARES E CEREBROVASCULARES'), ('GESTANTE', 'GESTANTE'), ('HEMOGLOBINOPATIA GRAVE', 'HEMOGLOBINOPATIA GRAVE'), ('HIPERTENSAO', 'HIPERTENSAO'), ('IMUNOSSUPRIMIDO', 'IMUNOSSUPRIMIDO'), ('OBESIDADE GRAVE', 'OBESIDADE GRAVE'), ('PACIENTE ONCOLOGICO', 'PACIENTE ONCOLOGICO'), ('PESSOA VIVENDO COM HIV', 'PESSOA VIVENDO COM HIV'), ('PNEUMOPATIA CRONICA GRAVE', 'PNEUMOPATIA CRONICA GRAVE'), ('PUERPERA', 'PUERPERA'), ('SINDROME DE DOWN', 'SINDROME DE DOWN'), ('TERAPIA RENAL SUBSTITUTIVA/DIALISE', 'TERAPIA RENAL SUBSTITUTIVA/DIALISE'), ('TRANSPLANTADO DE ORGAO SOLIDO E MEDULA OSSEA', 'TRANSPLANTADO DE ORGAO SOLIDO E MEDULA OSSEA')], default=None, max_length=378, verbose_name='Comorbidades')),
                ('CRM_medico_resp', models.IntegerField(blank=True, default=None, null=True, verbose_name='CRM médico responsável')),
                ('num_BPC', models.IntegerField(blank=True, default=None, null=True, verbose_name='Número do BPC')),
                ('dose', models.CharField(choices=[('UNICA', 'UNICA'), ('1º DOSE', '1º DOSE'), ('2º DOSE', '2º DOSE')], max_length=16, verbose_name='Dose')),
                ('via_admn', models.CharField(choices=[('EV', 'ENDOVENOSA'), ('ID', 'INTRADERMICA'), ('IM', 'INTRAMUSCULAR'), ('O', 'ORAL'), ('SC', 'SUBCUTANEA')], max_length=20, verbose_name='Via de Administração')),
                ('local_admn', models.CharField(choices=[('DD', 'DELTOIDE DIREITO'), ('DE', 'DELTOIDE ESQUERDO'), ('G', 'GLUTEO'), ('FL', 'LOCAL DO FERIMENTO'), ('VLD', 'VASTO LATERAL DA COXA DIREITO'), ('VLE', 'VASTO LATERAL DA COXA ESQUERDA'), ('VGD', 'VENTROGLUTEO DIREITO'), ('VGE', 'VENTROGLUTEO ESQUERDO')], max_length=20, verbose_name='Local de Administração')),
                ('grupo', models.CharField(choices=[('AEROVIARIOS', 'AEROVIARIOS'), ('COMORBIDADE', 'COMORBIDADE'), ('ESTUDO CLINICO', 'ESTUDO CLINICO'), ('IDOSO', 'IDOSO'), ('IDOSO EM ILPI', 'IDOSO EM ILPI'), ('INDIGENAS', 'INDIGENAS'), ('METROVIARIOS/CPTM', 'METROVIARIOS/CPTM'), ('MOTORISTAS E COBRADORES DE ONIBUS', 'MOTORISTAS E COBRADORES DE ONIBUS'), ('PESSOA >= 18 ANOS PORTADORA DE DEFICIENCIA RESIDENTES EM RI', 'PESSOA >= 18 ANOS PORTADORA DE DEFICIENCIA RESIDENTES EM RI'), ('PESSOA COM DEFICIENCIA', 'PESSOA COM DEFICIENCIA'), ('PESSOA COM DEFICIENCIA PERMANENTE SEVERA', 'PESSOA COM DEFICIENCIA PERMANENTE SEVERA'), ('POPULACAO EM GERAL', 'POPULACAO EM GERAL'), ('POPULACAO EM SITUACAO DE RUA', 'POPULACAO EM SITUACAO DE RUA'), ('PORTUARIOS', 'PORTUARIOS'), ('QUILOMBOLA', 'QUILOMBOLA'), ('RIBEIRINHAS', 'RIBEIRINHAS'), ('TRABALHADOR DA EDUCACAO', 'TRABALHADOR DA EDUCACAO'), ('TRABALHADOR DA SEGURANCA PUBLICA', 'TRABALHADOR DA SEGURANCA PUBLICA'), ('TRABALHADOR DE SAUDE', 'TRABALHADOR DE SAUDE')], max_length=100, verbose_name='Grupo de Atendimento')),
                ('estrategia', models.CharField(choices=[('CAMPANHA INDISCRIMINADA', 'CAMPANHA INDISCRIMINADA')], max_length=100, verbose_name='Estratégia')),
                ('data_aplic', models.DateField(null=True, verbose_name='Data de Aplicação')),
                ('data_apraz', models.DateField(blank=True, null=True, verbose_name='Data de Aprazamento')),
                ('estado_1_dose', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapa'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceara'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goias'), ('MA', 'Maranhao'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Para'), ('PB', 'Paraiba'), ('PR', 'Parana'), ('PE', 'Pernambuco'), ('PI', 'Piaui'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondonia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'Sao Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=100, null=True, verbose_name='Estado Primeira Dose')),
                ('pais_1_dose', models.CharField(blank=True, choices=[('AF', 'Afeganistao'), ('ZA', 'Africa do Sul'), ('AL', 'Albania'), ('DE', 'Alemanha'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AQ', 'Antartida'), ('AG', 'Antigua e Barbuda'), ('AN', 'Antilhas Holandesas'), ('SA', 'Arabia Saudita'), ('DZ', 'Argelia'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AW', 'Aruba'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ  ', 'Azerbaijao'), ('BS', 'Bahamas'), ('BH', 'Bahrein'), ('BD', 'Bangladesh'), ('BB', 'Barbados'), ('BY', 'Belarus'), ('BE', 'Belgica'), ('BZ', 'Belize'), ('BJ', 'Benin'), ('BM', 'Bermudas'), ('BO', 'Bolivia'), ('BA', 'Bosnia-Herzegovina'), ('BW', 'Botsuana'), ('BR', 'Brasil'), ('BN', 'Brunei'), ('BG', 'Bulgaria'), ('BF', 'Burkina Fasso'), ('BI', 'Burundi'), ('BT', 'Butao'), ('CV', 'Cabo Verde'), ('CM', 'Camaroes'), ('KH', 'Camboja'), ('CA', 'Canada'), ('KZ', 'Cazaquistao'), ('TD', 'Chade'), ('CL', 'Chile'), ('CN', 'China'), ('CY', 'Chipre'), ('SG', 'Cingapura'), ('CO', 'Colombia'), ('CG', 'Congo'), ('KP', 'Coreia do Norte'), ('KR', 'Coreia do Sul'), ('CI', 'Costa do Marfim'), ('CR', 'Costa Rica'), ('HR', 'Croacia (Hrvatska)'), ('CU', 'Cuba'), ('DK', 'Dinamarca'), ('DJ', 'Djibuti'), ('DM', 'Dominica'), ('EG', 'Egito'), ('SV', 'El Salvador'), ('AE', 'Emirados Arabes Unidos'), ('EC', 'Equador'), ('ER', 'Eritreia'), ('SK', 'Eslovaquia'), ('SI', 'Eslovenia'), ('ES', 'Espanha'), ('US', 'Estados Unidos'), ('EE', 'Estonia'), ('ET', 'Etiopia'), ('FJ', 'Fiji'), ('PH', 'Filipinas'), ('FI', 'Finlandia'), ('FR', 'Franca'), ('GA', 'Gabao'), ('GM', 'Gambia'), ('GH', 'Gana'), ('GE', 'Georgia'), ('GI', 'Gibraltar'), ('GB', 'Gra-Bretanha (Reino Unido, UK)'), ('GD', 'Granada'), ('GR', 'Grecia'), ('GL', 'Groelandia'), ('GP', 'Guadalupe'), ('GU', 'Guam (Territorio dos Estados Unidos)'), ('GT', 'Guatemala'), ('G', 'Guernsey'), ('GY', 'Guiana'), ('GF', 'Guiana Francesa'), ('GN', 'Guine'), ('GQ', 'Guine Equatorial'), ('GW', 'Guine-Bissau'), ('HT', 'Haiti'), ('NL', 'Holanda'), ('HN', 'Honduras'), ('HK', 'Hong Kong'), ('HU', 'Hungria'), ('YE', 'Iemen'), ('BV', 'Ilha Bouvet (Territorio da Noruega)'), ('IM', 'Ilha do Homem'), ('CX', 'Ilha Natal'), ('PN', 'Ilha Pitcairn'), ('RE', 'Ilha Reuniao'), ('AX', 'Ilhas Aland'), ('KY', 'Ilhas Cayman'), ('CC', 'Ilhas Cocos'), ('KM', 'Ilhas Comores'), ('CK', 'Ilhas Cook'), ('FO', 'Ilhas Faroes'), ('FK', 'Ilhas Falkland (Malvinas)'), ('GS', 'Ilhas Georgia do Sul e Sandwich do Sul'), ('HM', 'Ilhas Heard e McDonald (Territorio da Australia)'), ('MP', 'Ilhas Marianas do Norte'), ('MH', 'Ilhas Marshall'), ('UM', 'Ilhas Menores dos Estados Unidos'), ('NF', 'Ilhas Norfolk'), ('SC', 'Ilhas Seychelles'), ('SB', 'Ilhas Solomao'), ('SJ', 'Ilhas Svalbard e Jan Mayen'), ('TK', 'Ilhas Tokelau'), ('TC', 'Ilhas Turks e Caicos'), ('VI', 'Ilhas Virgens (Estados Unidos)'), ('VG', 'Ilhas Virgens (Inglaterra)'), ('WF', 'Ilhas Wallis e Futuna'), ('IN', 'india'), ('ID', 'Indonesia'), ('IR', 'Ira'), ('IQ', 'Iraque'), ('IE', 'Irlanda'), ('IS', 'Islandia'), ('IL', 'Israel'), ('IT', 'Italia'), ('JM', 'Jamaica'), ('JP', 'Japao'), ('JE', 'Jersey'), ('JO', 'Jordania'), ('KE', 'Kenia'), ('KI', 'Kiribati'), ('KW', 'Kuait'), ('LA', 'Laos'), ('LV', 'Latvia'), ('LS', 'Lesoto'), ('LB', 'Libano'), ('LR', 'Liberia'), ('LY', 'Libia'), ('LI', 'Liechtenstein'), ('LT', 'Lituania'), ('LU', 'Luxemburgo'), ('MO', 'Macau'), ('MK', 'Macedonia (Republica Yugoslava)'), ('MG', 'Madagascar'), ('MY', 'Malasia'), ('MW', 'Malaui'), ('MV', 'Maldivas'), ('ML', 'Mali'), ('MT', 'Malta'), ('MA', 'Marrocos'), ('MQ', 'Martinica'), ('MU', 'Mauricio'), ('MR', 'Mauritania'), ('YT', 'Mayotte'), ('MX', 'Mexico'), ('FM', 'Micronesia'), ('MZ', 'Mocambique'), ('MD', 'Moldova'), ('MC', 'Monaco'), ('MN', 'Mongolia'), ('ME', 'Montenegro'), ('MS', 'Montserrat'), ('MM', 'Myanma'), ('NA', 'Namibia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NI', 'Nicaragua'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('NU', 'Niue'), ('NO', 'Noruega'), ('NC', 'Nova Caledonia'), ('NZ', 'Nova Zelandia'), ('OM', 'Oma'), ('PW', 'Palau'), ('PA', 'Panama'), ('PG', 'Papua-Nova Guine'), ('PK', 'Paquistao'), ('PY', 'Paraguai'), ('PE', 'Peru'), ('PF', 'Polinesia Francesa'), ('PL', 'Polonia'), ('PR', 'Porto Rico'), ('PT', 'Portugal'), ('QA', 'Qatar'), ('KG', 'Quirguistao'), ('CF', 'Republica Centro-Africana'), ('CD', 'Republica Democratica do Congo'), ('DO', 'Republica Dominicana'), ('CZ', 'Republica Tcheca'), ('RO', 'Romenia'), ('RW', 'Ruanda'), ('RU', 'Russia (antiga URSS) - Federacao Russa'), ('EH', 'Saara Ocidental'), ('VC', 'Saint Vincente e Granadinas'), ('AS', 'Samoa Americana'), ('WS', 'Samoa Ocidental'), ('SM', 'San Marino'), ('SH', 'Santa Helena'), ('LC', 'Santa Lucia'), ('BL', 'Sao Bartolomeu'), ('KN', 'Sao Cristovao e Nevis'), ('MF', 'Sao Martim'), ('ST', 'Sao Tome e Principe'), ('SN', 'Senegal'), ('SL', 'Serra Leoa'), ('RS', 'Servia'), ('SY', 'Siria'), ('SO', 'Somalia'), ('LK', 'Sri Lanka'), ('PM', 'St. Pierre and Miquelon'), ('SZ', 'Suazilandia'), ('SD', 'Sudao'), ('SE', 'Suecia'), ('CH', 'Suica'), ('SR', 'Suriname'), ('TJ', 'Tadjiquistao'), ('TH', 'Tailandia'), ('TW', 'Taiwan'), ('TZ', 'Tanzania'), ('IO', 'Territorio Britanico do Oceano indico'), ('TF', 'Territorios do Sul da Franca'), ('PS', 'Territorios Palestinos Ocupados'), ('TP', 'Timor Leste'), ('TG', 'Togo'), ('TO', 'Tonga'), ('TT', 'Trinidad and Tobago'), ('TN', 'Tunisia'), ('TM', 'Turcomenistao'), ('TR', 'Turquia'), ('TV', 'Tuvalu'), ('UA', 'Ucrania'), ('UG', 'Uganda'), ('UY', 'Uruguai'), ('UZ', 'Uzbequistao'), ('VU', 'Vanuatu'), ('VA', 'Vaticano'), ('VE', 'Venezuela'), ('VN', 'Vietna'), ('ZM', 'Zambia'), ('ZW', 'Zimbabue')], max_length=100, null=True, verbose_name='País Primeira Dose')),
                ('imunobiologico', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='covidlocal.imunobiologico', verbose_name='Imunobiológico')),
                ('lote', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='covidlocal.lote', verbose_name='Lote')),
                ('paciente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='covidlocal.paciente', verbose_name='Paciente')),
                ('vacinador', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vacinador')),
            ],
        ),
    ]
