# Generated by Django 3.2.4 on 2021-06-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidlocal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='id_cand',
            new_name='CNS',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='isCNS',
        ),
        migrations.AddField(
            model_name='paciente',
            name='CPF',
            field=models.IntegerField(blank=True, default=None, unique=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='zona',
            field=models.CharField(choices=[('RURAL', 'RURAL'), ('URBANA', 'URBANA')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
