# Generated by Django 3.2.4 on 2021-06-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidlocal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='zona',
            field=models.CharField(choices=[('RURAL', 'RURAL'), ('URBANA', 'URBANA')], default='RURAL', max_length=6),
            preserve_default=False,
        ),
    ]
