# Generated by Django 3.2.4 on 2021-06-19 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidlocal', '0002_auto_20210618_1810'),
        ('covidlocal', '0002_paciente_zona'),
    ]

    operations = [
    ]
