# Generated by Django 3.2.4 on 2021-06-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidlocal', '0004_alter_paciente_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dataNascimento',
            field=models.DateField(),
        ),
    ]
