# Generated by Django 3.2.4 on 2021-06-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidlocal', '0005_alter_paciente_datanascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='CNS',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='CPF',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
