# Generated by Django 3.2.4 on 2021-06-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidlocal', '0006_auto_20210619_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='CNS',
            field=models.IntegerField(blank=True, default=None, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='CPF',
            field=models.IntegerField(blank=True, default=None, max_length=11, null=True, unique=True),
        ),
    ]
